server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: true
  retryableStatusCodes: 404,403,503,500
  
tcloud:
  ribbon:
    connection-timeout: 1000
    read-timeout: 2000
    retry:
      max-attempts: 2
#      retryable-exceptions:
#        - java.net.SocketTimeoutException
#        - java.lang.NullPointerException
#        - org.springframework.cloud.client.loadbalancer.ClientHttpResponseStatusCodeException
  context:
    system-init: 
      - apiInit
      
#    api: 
#      meta-location: data/api.xml
     
#tcloud:
#  context:
#    api:
#      location: classpath:/data/api.xml

spring:
  application:
    name: cloud-service01
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
    
  
  redis:
    host: 192.168.8.176
    port: 6379
  cloud:
    stream:
      default-binder: kafka
      bindings:
        broadcastOutput:
          destination: broadcastMessage2
        groupMessageOutput:
          destination: groupMessage
        broadcastInput: 
          destination: broadcastMessage2
        groupMessageInput: 
          destination: groupMessage
          
      kafka:
        binder:
          brokers:
            - 192.168.8.60:9092
          configuration:
            metadata:
              fetch:
                timeout:
                  ms: 2000  
