server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

tcloud:
  context:
    system-init: 
      - apiInit
    api:
      location: data/api.xml
     
#tcloud:
#  context:
#    api:
#      location: classpath:/data/api.xml

spring:
  application:
    name: cloud-web-service01
    
  redis:
    host: 192.168.8.176
    port: 6379
    
#  cloud:
#    stream:
#      default-binder: kafka
#      bindings:
#        broadcastInput: 
#          destination: broadcastMessage2
#        groupMessageInput: 
#          destination: groupMessage
#          
#      kafka:
#        binder:
#          brokers:
#            - 192.168.8.91:9092
#          configuration:
#            metadata:
#              fetch:
#                timeout:
#                  ms: 2000  
