server:
  port: 8001
  
spring:
  application:
    name: cloud-web-service01
  cloud:
    stream:
      default-binder: kafka
      bindings:
        broadcastInput: 
          destination: broadcastMessage2
        groupMessageInput: 
          destination: groupMessage
          
      kafka:
        binder:
          brokers:
            - 192.168.8.91:9092
          configuration:
            metadata:
              fetch:
                timeout:
                  ms: 2000  
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/