server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: true
#  retryableStatusCodes: 404,403,503
  
tcloud:
  ribbon:
    connection-timeout: 1000
    read-timeout: 2000
  context:
    system-init: 
      - apiInit
#    api: 
#      meta-location: data/api.xml
     
#tcloud:
#  context:
#    api:
#      location: classpath:/data/api.xml

spring:
  application:
    name: cloud-service01
    
  redis:
    host: 192.168.8.176
    port: 6379
    
#  cloud:
#    stream:
#      default-binder: kafka
#      bindings:
#        broadcastInput: 
#          destination: broadcastMessage2
#        groupMessageInput: 
#          destination: groupMessage
#          
#      kafka:
#        binder:
#          brokers:
#            - 192.168.8.91:9092
#          configuration:
#            metadata:
#              fetch:
#                timeout:
#                  ms: 2000  
