server:
  port: 8002
  
spring:
  application:
    name: cloud-web-service02
  
  data:
    elasticsearch:
      cluster-name: elasticsearch #默认值为elasticsearch，集群的唯一标识
      cluster-nodes: 127.0.0.1:9300 #多节点用逗号隔开
      repositories:
        enabled: true

#  cloud:
#    zookeeper:
#      connect-string: 192.168.8.91:2181
#      connect-string: 192.168.8.167:2181,192.168.8.168:2181,192.168.8.169:2181
#      discovery:
#        instance-host: 192.168.8.91
#        instance-port: ${server.port}
#        instance-id: ${spring.cloud.zookeeper.discovery.instance-host}:${spring.cloud.zookeeper.discovery.instance-port}

 
#  cloud:
#    stream:
#      default-binder: kafka
#      bindings:
#        broadcastOutput: 
#          destination: broadcastMessage2
#            
#        groupMessageOutput: 
#          destination: groupMessage
#          
#      kafka:
#        binder:
#          brokers:
#            - 192.168.8.91:9092
#          configuration:
#            metadata:
#              fetch:
#                timeout:
#                  # 获取metadata的超时时间
#                  ms: 2000  
      
