server:
  port: 8002
  
spring:
  application:
    name: cloud-web-service02
  
  cloud:
    stream:
      default-binder: kafka
      bindings:
        broadcastOutput: 
          destination: broadcastMessage
            
        groupMessageOutput: 
          destination: groupMessage
          
      kafka:
        binder:
          brokers:
            - 192.168.8.91:9092
          configuration:
            metadata:
              fetch:
                timeout:
                  # 获取metadata的超时时间
                  ms: 2000  
      
